greeting: "Welcome to the Number Guessing Game!\nI'm thinking of a number between 1 and 100.\nYou have a limited number of chances to guess the correct number."

player: "Enter your player name: "

difficulty: "Please select the difficulty level:\n1. Easy (10 chances)\n2. Medium (5 chances)\n3. Hard (3 chances)\n\nEnter your choice: "

level: "Great! You have selected the %s difficulty level.\nLet's start the game!"

guess: "Enter your guess: "

greater: "Incorrect! The number is greater than %d."

less: "Incorrect! The number is less than %d."

equal: "Congratulations! You guessed the correct number in %v with %d attempts."

max_attempts: "You've used all your chances! Better luck next time."

very_close_1: "You're extremely close! Just one more guess and you'll have it!"

very_close_2: "You're quite close! A little adjustment and you'll find the number!"

very_close_3: "You're getting warmer! Keep those guesses coming, you're on the right path!"

close_1: "You're getting closer! A bit more focus will lead you to the answer!"

close_2: "You're not too far off! A slight change in your guesses could make a difference!"

far: "You're a little far from the target!"

very_far: "You're very far from the correct number. But don't give up!"

again: "Do you want to play again?\n1. Yes\n2. No\n\nEnter your choice: "

bye: "It was a pleasure to see you! Until next time!"

newline: "\n"

spacer: "\n\n"
