greeting: |
  Welcome to the Number Guessing Game!
  I'm thinking of a number between 1 and 100.
  You have a limited number of chances to guess the correct number.

  Please select the difficulty level:
  1. Easy (10 chances)
  2. Medium (5 chances)
  3. Hard (3 chances)
difficulty: "Enter your choice: "
level: |
  Great! You have selected the %s difficulty level.
  Let's start the game!

guess: "Enter your guess: "
greater: "Incorrect! The number is greater than %d."
less: "Incorrect! The number is less than %d."
equal: "Congratulations! You guessed the correct number in %d attempts."
max_attempts: "Sorry, you have used all your attempts. Better luck next time!"
newline: "\n"
spacer: "\n\n"